name: myspace_design_system
description: "MySpace Design System"
version: 0.0.1
homepage: www.shoh.dev

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  bot_toast: ^4.1.3
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter: